apps/static_page/urls.py
from django.urls import include, path, re_path

from .views import home_view, about_view

app_name = 'static_page'

urlpatterns = [
    path('', home_view, name='home'),
    path('about/', about_view, name='about'),
]

config/urls.py
from django.conf import settings
from django.urls import include, path, re_path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

#from django.contrib.sitemaps.views import sitemap
from django.conf.urls.i18n import i18n_patterns
#{%- if cookiecutter.use_async == 'y' %}
#from django.contrib.staticfiles.urls import staticfiles_urlpatterns
#{%- endif %}
#{%- if cookiecutter.use_drf == 'y' %}
#from rest_framework.authtoken.views import obtain_auth_token
#{%- endif %}
#from posts.feeds import LastEntriesFeed
#from posts.sitemaps import PostSitemap

#sitemaps = {
#    'posts': PostSitemap,
#}


#from import subscription, unsubscription

urlpatterns = [
    #path("", TemplateView.as_view(template_name="pages/home.html"), 
    #    name="home"
    #),
    #path(
    #    "about/",
    #    TemplateView.as_view(template_name="pages/about.html"),
    #    name="about",
    #),
    path('', include('static_page.urls')),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management0
    #re_path("users/", include("base_new.users.urls", namespace="users")),
    # other urls
    re_path('accounts/', include('allauth.urls')),
    re_path('users/', include('users.urls')),
    #re_path('service/', include('services.urls')),
    # Your stuff: custom urls includes go here
    re_path('robots\.txt', include('robots.urls')),
    #path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
    #     name='django.contrib.sitemaps.views.sitemap'
    #)
] + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)
#{%- if cookiecutter.use_async == 'y' %}
#if settings.DEBUG:
    # Static file serving when using Gunicorn + Uvicorn for local web socket development
#    urlpatterns += staticfiles_urlpatterns()
#{%- endif %}
#{% if cookiecutter.use_drf == 'y' %}
# API URLS
#urlpatterns += [
    # API base url
#    path("api/", include("config.api_router")),
    # DRF auth token
#    path("auth-token/", obtain_auth_token),
#]
#{%- endif %}
if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] \
            + urlpatterns

base_templates/templates/403_csrf.html
{% extends "base.html" %}

{% block title %}Forbidden (403){% endblock %}

{% block content %}
<h1>Forbidden (403)</h1>

<p>CSRF verification failed. Request aborted.</p>
{% endblock content %}

base_templates/templates/_account_bar.html
{% load i18n %}
{% load account %}

<!-- Nav Item - User Information -->
{% if request.user.is_authenticated %}
<li class="nav-item dropdown no-arrow">
    <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <span class="mr-2 d-none d-lg-inline text-gray-600 small">{% user_display request.user %}</span>
    <!--<img class="img-profile rounded-circle" src="https://source.unsplash.com/QAB-WJcbgJk/60x60">-->
    </a>
    <!-- Dropdown - User Information -->
    <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
        <a class="dropdown-item" href="/users/{% user_display user %}">
            <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
            {% trans "Profile" %}
        </a>
        <div class="dropdown-divider"></div>
        <a class="dropdown-item" href="{% url 'account_logout' %}">
            <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
            {% trans "Log out" %}
        </a>
    </div>
</li>
{% else %}
<li class="nav-item dropdown no-arrow">
    <a class="nav-link" href="{% url 'account_login' %}" role="button">
        <span class="mr-2 d-none d-lg-inline text-gray-600 small">{% trans "Log in" %}</span>
        <i class="fas fa-sign-in-alt fa-sm fa-fw mr-2 text-gray-400"></i>
    </a>
</li>

<div class="topbar-divider d-none d-sm-block"></div>

<li class="nav-item">
    <a class="nav-link" href="{% url 'account_signup' %}" role="button">
        <span class="mr-2 d-none d-lg-inline text-gray-600 small">{% trans "Sign up" %}</span>
        <i class="fas fa-user-plus fa-sm fa-fw mr-2 text-gray-400"></i>
    </a>
</li>

{% endif %}

base_templates/templates/_footer.html
{% load i18n static %}
<!-- Footer -->
  <div class="container my-auto">
      <div class="copyright text-center my-auto">
        <span>Copyright &copy; <script>document.write(new Date().getFullYear());</script> Create By <a href="https://github.com/agiledesign2" target="_blank">David Gomez</a> <i class="fas fa-heart" aria-hidden="true"></i></span>
      </div>
  </div>
<!-- End of Footer -->

base_templates/templates/_menu.html
{% load i18n static %}
<!-- Topbar -->
<nav class="navbar navbar-expand navbar-light bg-white topbar static-top shadow">

  <!-- Sidebar Toggle (Topbar) -->
   <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
     <i class="fa fa-bars"></i>
   </button>

  {# <img src="{% static 'images/Perthshire-Logo.gif' %}" alt="Perthshire Logo" class=""> #}

  <!-- Topbar Search -->
  <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search" action="{% url 'posts:search' %}" method="GET">
    <div class="input-group">
      <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2" name="q">
      <div class="input-group-append">
        <button class="btn btn-primary" type="button">
          <i class="fas fa-search fa-sm"></i>
        </button>
      </div>
    </div>
  </form>

  <!-- Topbar Navbar -->
  <ul class="navbar-nav ml-auto">
    <!-- Nav Item - Search Dropdown (Visible Only XS) -->
    <li class="nav-item dropdown no-arrow d-sm-none">
      <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="fas fa-search fa-fw"></i>
      </a>
      <!-- Dropdown - Messages -->
      <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in" aria-labelledby="searchDropdown">
        <form class="form-inline mr-auto w-100 navbar-search" action="{% url 'posts:search' %}" method="GET">
          <div class="input-group">
            <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2" name="q">
            <div class="input-group-append">
              <button class="btn btn-primary" type="button">
                <i class="fas fa-search fa-sm"></i>
              </button>
            </div>
          </div>
        </form>
      </div>
    </li>
    {% include "_account_bar.html" %}
  </ul>

</nav>
<!-- End of Topbar -->

base_templates/templates/_messages.html
{% comment %}
{% for message in messages %}
    <div class="message {{ message.tags }}">
        <button type="button" class="close" data-dismiss="message"><i  class="fas fa-times"></i></button>
        {{ message }}
    </div>
{% endfor %}
{% endcomment %}
{% if messages %}
    <ul class="messages">
      {% for message in messages %}
        <li class="{{ message.tags }}">
          {{ message|safe }}
            <a href="#" class="close">x</a>
        </li>
      {% endfor %}
    </ul>
{% endif %}

base_templates/templates/_nav.html
{% load i18n %}
{% load account %}

{% with request.resolver_match.url_name as url_name %}
<!-- Sidebar -->
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion toggled" id="accordionSidebar">

  <!-- Sidebar - Brand -->
  <a class="sidebar-brand d-flex align-items-center justify-content-center" href="/">
    <div class="sidebar-brand-icon rotate-n-15">
      <i class="fab fa-python"></i>
    </div>
    <div class="sidebar-brand-text mx-3">Menu</div>
  </a>

  <!-- Divider -->
  <hr class="sidebar-divider my-0">

  <!-- Nav Item - Dashboard -->
  <li class="nav-item {% if url_name == 'search' %}active{% endif %}">
    <a class="nav-link" href="/blog/search/">
      <i class="fas fa-fw fa-search"></i>
      <span>Search</span></a>
  </li>

  <!-- Divider -->
  <hr class="sidebar-divider">
  <li class="nav-item {% if url_name == 'home' %}active{% endif %}">
    <a class="nav-link" href="/">
      <i class="fas fa-fw fa-home"></i>
      <span>Home</span></a>
  </li>
  <li class="nav-item {% if url_name == 'index' %}active{% endif %}">
    <a class="nav-link" href="{% url 'posts:index' %}">
      <i class="fas fa-fw fa-blog"></i>
      <span>Blog</span></a>
  </li>
  <li class="nav-item {% if url_name == 'about' %}active{% endif %}">
    <a class="nav-link" href="{% url 'static_page:about' %}">
      <i class="fas fa-fw fa-info-circle"></i>
      <span>About</span></a>
  </li>
  <li class="nav-item {% if url_name == 'contact_form' %}active{% endif %}">
    <a class="nav-link" href="{% url 'contact_form' %}">
      <i class="fas fa-fw fa-address-card"></i>
      <span>Contact</span></a>
  </li>

  <!-- Divider -->
  <hr class="sidebar-divider d-none d-md-block">

  <!-- Sidebar Toggler (Sidebar) -->
  <div class="text-center d-none d-md-inline">
    <button class="rounded-circle border-0" id="sidebarToggle"></button>
  </div>

</ul>
{% endwith %}

base_templates/templates/_scripts.html
{% load static %}
    {# <script src="{% static 'js/jquery-migrate-3.0.0.js' %}" ></script> #}

base_templates/templates/_sidebar.html
{% load pinax_blog_tags %}
{% load pinax_comments_tags %}
{% load static %}
            <!--<div class="sidebar-box search-form-wrap">
              <form action="#" class="search-form">
                <div class="form-group">
                  <span class="icon fa fa-search"></span>
                  <input type="text" class="form-control" id="s" placeholder="Type a keyword and hit enter">
                </div>
              </form>
            </div> -->
            <!-- END sidebar-box -->
            <div class="sidebar-box">
              <div class="bio text-center">
                <img src="{% static 'images/person_1.jpg' %}" alt="David Gomez Desarrollador Python" class="img-fluid">
                <div class="bio-body">
                  <h2>David Gomez</h2>
                  <p>Hola soy David Gómez, soy un Desarrollador y Programador de software el cual Trabaja como FreeLancer. Me dedico al desarrollo, diseño de sitios web, el desarrollo de aplicaciones móviles y de escritorio.</p>
                  <p><a href="/about/" class="btn btn-primary btn-sm">Mas sobre mi</a></p>
                  <p class="social">
                    <a href="#" class="p-2"><span class="fab fa-facebook"></span></a>
                    <a href="#" class="p-2"><span class="fab fa-twitter"></span></a>
                    <a href="#" class="p-2"><span class="fab fa-instagram"></span></a>
                    <a href="#" class="p-2"><span class="fab fa-youtube"></span></a>
                  </p>
                </div>
              </div>
            </div>
            <!-- END sidebar-box -->  
            <div class="sidebar-box">
              <h3 class="heading">Popular Posts</h3>
              <div class="post-entry-sidebar">
                <ul>
                {% latest_blog_posts as latest_ga %}
                {% for ga in latest_ga %}
                  {% include "pinax/blog/latest_post.html" %}
                {% endfor %}
                </ul>
              </div>
            </div>
            <!-- END sidebar-box -->

            <div class="sidebar-box">
              <h3 class="heading">Sections</h3>
              <ul class="tags">
              {% blog_sections as sections %}
              {% for section in sections %}
                <!--<li><a href="/search/?q={{ section.name }}">{{ section.name }}</a></li>-->
                <li><a href="/blog/section/{{ section.name }}">{{ section.name }}</a></li>
              {% endfor %}
              </ul>
            </div>

base_templates/templates/_styles.html
{% load static %}
	{# <link href="{% static 'css/animate.css' %}" rel="stylesheet"> #}

base_templates/templates/base.html
{% load i18n static google_analytics_js %}

<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE }}">
    <head {% block meta_head %}{% endblock %}>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>{% block head_title_base %} {% block head_title %} {{ settings.SITE_TITLE }} {% endblock %} | {{ settings.SITE_NAME }} {% endblock %}</title>
        {% block viewport %}
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        {% endblock %}

        {% block meta_data %}
        {% include "meta/meta.html" %}
        {% endblock %}

    	<!-- Favicon -->
    	<link href="{% static 'img/favicons/favicon.ico' %}" rel="icon">

    	<!-- Core Stylesheet -->
    	<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" type="text/css">
    	<link href="{% static 'css/all.min.css' %}" rel="stylesheet" type="text/css">

      <!-- Theme stuff: Theme dep -->
      <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet" type="text/css">
      <link href="{% static 'css/base.css' %}" rel="stylesheet" type="text/css">

      	{% include "_styles.html" %}
      	{% block styles %}{% endblock %}

      {% google_analytics_js %}
    </head>
    <body class="{% block body_class_base %}{% block body_class %}{% endblock %}{% endblock %}" id="{% block body_id %}page-top{% endblock %}" {% block body_extra_attributes %}{% endblock %}>
        <!-- Page Wrapper -->
  		<div id="wrapper">
  			{% block nav %}{% include "_nav.html" %}{% endblock %}

        	<!-- Content Wrapper -->
    		<div id="content-wrapper" class="d-flex flex-column">

      			<!-- Main Content -->
      			<div id="content">

              {% block topbar_base %}
              {% block topbar %}

              {% include "_menu.html" %}
      
              {% endblock %}
              {% endblock %}


              {% block body_base %}
        			<!-- Begin Page Content -->
        			<div class="container-fluid mt-4">

        				{% block content_left %}{% endblock %}
    
        				{% block Categorie %}{% endblock %}
        				{% block seccion %}{% endblock %}
                {% block messages %}{% include "_messages.html" %}{% endblock %}
        				{% block body %}
                {% block content %}{% endblock %}
                {% endblock %}

        			</div>
        			<!-- /.container-fluid -->

      			</div>
      			<!-- End of Main Content -->

            <footer class="sticky-footer bg-white">
        		{% block footer_base %}
            {% endblock %}
            {% block footer %}{% include "_footer.html" %}{% endblock %}
            </footer>

    	    </div>
   		 	<!-- End of Content Wrapper -->

  		</div>
  		<!-- Scroll to Top Button-->
  		<a class="scroll-to-top rounded" href="#page-top">
    		<i class="fas fa-angle-up"></i>
  		</a>
  		<!-- End of Page Wrapper -->
        {% block scripts_base %}
      	<!-- jQuery Plugins -->
      	<script src="{% static 'js/jquery.min.js' %}" ></script>
        <script src="{% static 'js/popper.min.js' %}" ></script> 
    
      	<!-- Required by Bootstrap v4.1.1 -->
      	<script src="{% static 'js/bootstrap.min.js' %}"></script>
      	<script src="{% static 'js/html5shiv.min.js' %}"></script> 
      	<!-- Required for Django Ajax -->
      	<script src="{% static 'js/eldarion-ajax.min.js' %}"></script>
    	  <script src="{% static 'js/csrf.js' %}"></script>

        <!-- Theme stuff: Theme dep -->
        <script src="{% static 'js/jquery.easing.min.js' %}"></script>
        <script src="{% static 'js/sb-admin-2.min.js' %}"></script>
        <script src="{% static 'js/main.js' %}"></script>
        {% comment %}
      	<!-- Your stuff: Third-party javascript libraries go here -->
      	<!--<script src="{% static 'js/all.min.js' %}"></script>-->
      	<!-- place project specific Javascript in this file -->
    	  <!-- All Plugins JS -->
    	  <!-- Active JS -->
    	  <!--<script src="{% static 'js/active.js' %}"></script>-->
        {% endcomment %}
      {% comment %}
      <script>
        var csrftoken = Cookies.get('csrftoken');
        function csrfSafeMethod(method) {
          // these HTTP methods do not require CSRF protection
          return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
        }
        $.ajaxSetup({
          beforeSend: function(xhr, settings) {
            if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
              xhr.setRequestHeader("X-CSRFToken", csrftoken);
            }
          }
        });

        $(document).ready(function(){
          {% block domready %}
          {% endblock %}
        });
      </script>
      {% endcomment %}
        {% block scripts %}{% include "_scripts.html" %}{% endblock %}
        {% block extra_body %}{% endblock %}
        {% endblock %}
        {% endblock %}
    </body>
</html>

base_templates/templates/site_base.html
{% extends "base.html" %}

{% load staticfiles %}
{% load i18n %}

base_templates/templates/subnav_base.html
{% load i18n %}

{% block body %}
    <div class="subnav-container">
        {% block subnav %}
        {% endblock %}
        <section>
            {% block content %}
            {% endblock %}
        </section>
    </div>
{% endblock %}